- name: check if pcs was already uninstalled
  command: pcs --version
  changed_when: false
  failed_when: false
  register: pcs_state

# 20.5.4.3 Destroying a quorum device
#
## pcs qdevice destroy net
#
- name: destroy qdevice
  command: >
    pcs qdevice destroy net
  when: pcs_state.rc == 0

### remove firewalld configuration
- name: check if firewalld is enabled
  command: firewall-cmd --state
  changed_when: false
  failed_when: false
  register: firewalld_state

- name: remove firewalld configuration for Pacemaker/Corosync (permanent)
  command: firewall-cmd --permanent --remove-service=high-availability
  register: result
  changed_when: '"NOT_ENABLED" not in result.stderr'
  when: firewalld_state.rc == 0

- name: remove firewalld configuration for Pacemaker/Corosync (runtime)
  command: firewall-cmd --remove-service=high-availability
  register: result
  changed_when: '"NOT_ENABLED" not in result.stderr'
  when: firewalld_state.rc == 0

#
- name: uninstall qnetd package
  yum:
    name: ['pcs', 'corosync-qnetd']
    state: absent


### Other cleanup stuff; not mentioned in the RHEL official documents
# remove pcsd directory
- name: cleanup /var/lib/pcsd
  file:
    path: /var/lib/pcsd/
    state: absent

# remove dependency packages
- name: uninstall corosync and pacemaker
  yum:
    name: corosync
    autoremove: yes
    state: absent

# remove hacluster users
- name: remove hacluster user
  user:
    name: hacluster
    state: absent
- name: remove haclient group
  group:
    name: haclient
    state: absent

# remove coroqnetd users
- name: remove coroqnetd user
  user:
    name: coroqnetd
    state: absent
- name: remove coroqnetd group
  group:
    name: coroqnetd
    state: absent

