- hosts: hacluster-shared
  become: true
  max_fail_percentage: 0
  gather_facts: no

  roles:
    - role: sharedstorage-setup
      tags: storage-setup

    - role: postgresql-install
      tags: install

    - role: postgresql-initdb
      tags: initdb
