## Preparation:
##   - 1. download both the RHEL8 base ISO image and the HA addon ISO image
##   - 2. set the RHEL8 base ISO image as a DVD media on the target hosts
##   - 3. copy and rename the HA addon ISO image into 
##        ./roles/repo-setup/files/rhel-8.0-ha-x86_64-dvd.iso

## # mount -o ro /dev/cdrom /media
- name: mount RHEL base media
  # aviod using mount module so not to modify /etc/fstab
  # ref. https://github.com/ansible/ansible/issues/48134
  command: >-
    env LANG=C mount -o ro /dev/cdrom /media
  register: result
  changed_when: result.rc == 0
  failed_when: result.rc != 0 and "already mounted" not in result.stderr

- name: check if the media is mounted correctly
  stat:
    path: /media/BaseOS
  register: stat_result
- name: fail if the base repo is not ready
  fail: msg="Failed to find the RHEL base repo. Check a DVD media."
  when: stat_result.stat.exists == False


## # mkdir /mnt/HighAvailability
## # mount -o loop,ro /var/tmp/rhel-8.0-ha-x86_64-dvd.iso /mnt/HighAvailability
- name: copy HA addon ISO media
  copy:
    src: rhel-8.0-ha-x86_64-dvd.iso
    dest: /var/tmp/
- name: setup the repository for HA addon
  file:
    path: /mnt/HighAvailability
    state: directory
- name: mount HA addon ISO media
  command: >-
    env LANG=C mount -o loop,ro /var/tmp/rhel-8.0-ha-x86_64-dvd.iso /mnt/HighAvailability
  register: result
  changed_when: result.rc == 0
  failed_when: result.rc != 0 and "already mounted" not in result.stderr

## # vi /etc/yum.repos.d/{rhel-media.repo,rhel-ha.repo}
- name: setup yum repository for the ISO media
  copy:
    src: "{{ item }}"
    dest: /etc/yum.repos.d/
  with_items:
    - rhel-media.repo
    - rhel-ha.repo
