# 20.5.4.2 Removing a quorum device
#
## # pcs quorum device remove
#
- name: remove a quorum device
  command: >
    pcs quorum device remove
  register: result
  changed_when: result.rc == 0
  failed_when: result.rc != 0 and "no quorum device is defined" not in result.stderr
  when: inventory_hostname == ansible_play_hosts[0]

#
#- name: deauth qdevice host

## # yum erase corosync-qdevice
- name: uninstall qdevice package
  yum:
    name: corosync-qdevice
    state: absent
